[project]
name = "akf3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "google-genai>=1.20.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.9.1",
    "pyyaml>=6.0.2",
]
